-- MySQL Script generated by MySQL Workbench
-- Sun Sep 24 01:21:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema penilaian
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema penilaian
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `penilaian` DEFAULT CHARACTER SET latin1 ;
USE `penilaian` ;

-- -----------------------------------------------------
-- Table `penilaian`.`aspnetroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`aspnetroles` (
  `Id` VARCHAR(128) NOT NULL,
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`aspnetusers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`aspnetusers` (
  `Id` VARCHAR(128) NOT NULL,
  `Email` VARCHAR(256) NULL DEFAULT NULL,
  `EmailConfirmed` TINYINT(1) NOT NULL,
  `PasswordHash` LONGTEXT NULL DEFAULT NULL,
  `SecurityStamp` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumber` LONGTEXT NULL DEFAULT NULL,
  `PhoneNumberConfirmed` TINYINT(1) NOT NULL,
  `TwoFactorEnabled` TINYINT(1) NOT NULL,
  `LockoutEndDateUtc` DATETIME NULL DEFAULT NULL,
  `LockoutEnabled` TINYINT(1) NOT NULL,
  `AccessFailedCount` INT(11) NOT NULL,
  `UserName` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`aspnetuserclaims`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`aspnetuserclaims` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `UserId` VARCHAR(128) NOT NULL,
  `ClaimType` LONGTEXT NULL DEFAULT NULL,
  `ClaimValue` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Id` (`Id` ASC),
  INDEX `UserId` (`UserId` ASC),
  CONSTRAINT `ApplicationUser_Claims`
    FOREIGN KEY (`UserId`)
    REFERENCES `penilaian`.`aspnetusers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`aspnetuserlogins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`aspnetuserlogins` (
  `LoginProvider` VARCHAR(128) NOT NULL,
  `ProviderKey` VARCHAR(128) NOT NULL,
  `UserId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`LoginProvider`, `ProviderKey`, `UserId`),
  INDEX `ApplicationUser_Logins` (`UserId` ASC),
  CONSTRAINT `ApplicationUser_Logins`
    FOREIGN KEY (`UserId`)
    REFERENCES `penilaian`.`aspnetusers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`aspnetuserroles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`aspnetuserroles` (
  `UserId` VARCHAR(128) NOT NULL,
  `RoleId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`UserId`, `RoleId`),
  INDEX `IdentityRole_Users` (`RoleId` ASC),
  CONSTRAINT `ApplicationUser_Roles`
    FOREIGN KEY (`UserId`)
    REFERENCES `penilaian`.`aspnetusers` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `IdentityRole_Users`
    FOREIGN KEY (`RoleId`)
    REFERENCES `penilaian`.`aspnetroles` (`Id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`pegawai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`pegawai` (
  `IdPegawai` INT(11) NOT NULL AUTO_INCREMENT,
  `Nama` VARCHAR(150) NOT NULL,
  `TempatLahir` VARCHAR(100) NOT NULL,
  `TanggalLahir` DATE NOT NULL,
  `NomorKartuPegawai` VARCHAR(45) NOT NULL,
  `Pendidikan` ENUM('SMP','SMA','S1','S2','S3') NOT NULL,
  `PangkatGolonganTerakhir` VARCHAR(100) NOT NULL,
  `JabatanAkhir` VARCHAR(100) NOT NULL,
  `Asal` ENUM('Papua','NonPapua') NOT NULL,
  `JenisKelamin` ENUM('L','P') NOT NULL,
  `NIP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPegawai`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`detailpegawai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`detailpegawai` (
  `IdPegawai` INT(11) NOT NULL,
  `TamatCPNS` DATE NULL DEFAULT NULL,
  `TamatGolongan` DATE NULL DEFAULT NULL,
  `TamatJabatan` DATE NULL DEFAULT NULL,
  `TanggunganSuamiIstri` INT(2) NULL DEFAULT NULL,
  `TanggunganAnak` INT(2) NULL DEFAULT NULL,
  `SKPejabat` ENUM('Presiden','Gubernur') NULL DEFAULT NULL,
  `NomorSK` VARCHAR(45) NULL DEFAULT NULL,
  `TanggalSK` DATE NULL DEFAULT NULL,
  `MasaKerja` INT(2) NULL DEFAULT NULL,
  `JenisKepegawaian` ENUM('PNSP','PNSD') NULL DEFAULT NULL,
  `StatusKepegawaian` ENUM('CPNS','PNS') NULL DEFAULT NULL,
  PRIMARY KEY (`IdPegawai`),
  INDEX `fk_DetailPegawai_Pegawai1_idx` (`IdPegawai` ASC),
  CONSTRAINT `fk_DetailPegawai_Pegawai1`
    FOREIGN KEY (`IdPegawai`)
    REFERENCES `penilaian`.`pegawai` (`IdPegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`kriteriapenilaian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`kriteriapenilaian` (
  `IdKriteria` INT(11) NOT NULL AUTO_INCREMENT,
  `Nama` VARCHAR(45) NULL DEFAULT NULL,
  `Keterangan` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IdKriteria`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`pejabatpenilai`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`pejabatpenilai` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `IdPegawai` INT(11) NOT NULL,
  `UserId` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_PejabatPenilai_Pegawai1_idx` (`IdPegawai` ASC),
  INDEX `fk_PejabatPenilai_users1_idx` (`UserId` ASC),
  CONSTRAINT `fk_PejabatPenilai_users1`
    FOREIGN KEY (`UserId`)
    REFERENCES `penilaian`.`aspnetusers` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PejabatPenilai_Pegawai1`
    FOREIGN KEY (`IdPegawai`)
    REFERENCES `penilaian`.`pegawai` (`IdPegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`penilaian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`penilaian` (
  `IdPenilaian` INT(11) NOT NULL,
  `TahunPeriode` INT(4) NULL DEFAULT NULL,
  `IdPegawai` INT(11) NOT NULL,
  `PejabatPenilaiId` INT(11) NOT NULL,
  PRIMARY KEY (`IdPenilaian`),
  INDEX `fk_Penilaian_Pegawai1_idx` (`IdPegawai` ASC),
  INDEX `fk_Penilaian_PejabatPenilai1_idx` (`PejabatPenilaiId` ASC),
  CONSTRAINT `fk_Penilaian_PejabatPenilai1`
    FOREIGN KEY (`PejabatPenilaiId`)
    REFERENCES `penilaian`.`pejabatpenilai` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Penilaian_Pegawai1`
    FOREIGN KEY (`IdPegawai`)
    REFERENCES `penilaian`.`pegawai` (`IdPegawai`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `penilaian`.`detailpenilaian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `penilaian`.`detailpenilaian` (
  `IdKriteria` INT(11) NOT NULL,
  `Nilai` DOUBLE NULL DEFAULT '0',
  `Id` INT(11) NOT NULL,
  `IdPenilaian` INT(11) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_DetailPenilaian_KriteriaPenilaian1_idx` (`IdKriteria` ASC),
  INDEX `fk_DetailPenilaian_Penilaian1_idx` (`IdPenilaian` ASC),
  CONSTRAINT `fk_DetailPenilaian_KriteriaPenilaian1`
    FOREIGN KEY (`IdKriteria`)
    REFERENCES `penilaian`.`kriteriapenilaian` (`IdKriteria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DetailPenilaian_Penilaian1`
    FOREIGN KEY (`IdPenilaian`)
    REFERENCES `penilaian`.`penilaian` (`IdPenilaian`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
